### ISSUE TITLE
Failed Authorization

### ISSUE THREAD

**Issue by hlyall01** [Tokariew/tomenet#1]
When trying to run docker build --tag tomenet-server-builder -f Dockerfile .\

D:\Documents\projects\tomenet-tokariew>docker build --tag tomenet-server-builder -f Dockerfile .\
[+] Building 2.3s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.1s 
 => => transferring dockerfile: 378B                                                                                                                                                                           0.0s 
 => [internal] load .dockerignore                                                                                                                                                                              0.1s 
 => => transferring context: 2B                                                                                                                                                                                0.0s 
 => ERROR [internal] load metadata for docker.io/library/fedora-minimal:34                                                                                                                                     2.1s 
------
 > [internal] load metadata for docker.io/library/fedora-minimal:34:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed 

is there a different command I would need to run for docker? I used to have it building with the old version on fedora:32 but docker seems to have died on me

**Comment by Tokariew** [comment]
Oh i see what is the problem i will fix it in next patch in moment

I was thinking for making patches for your version of server, based on your repo commits ;)

**Comment by Tokariew** [comment]
Error should be fixed
old fedora:32 should be still working
in b73a9e0 commit i added check to not compile if changes in main repo are older than week, you can remove this line to compile, before running `docker build`
```
{ [ "$num1" -lt 7 ] && test "${var1#*days}" != "$var1"; } || { cleanup && echo "Old version" && exit 0; }
```

i will add switch later for skipping compilation…

**Comment by hlyall01** [comment]
yeah, i ran into an issue where my docker wasnt creating the folders correctly so i couldnt build, ty for the help, i have a mac environment now so i might see how podman goes, will let you know if this is resolved but it looks like it should be.
